[Appearance]
color_scheme_path=/home/pang/.config/qt6ct/colors/noctalia.conf
custom_palette=true
style=Fusion

[Interface]
icon_theme=Papirus-Dark

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xf3\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xf3\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xf3)
