[General]
OverSpaceUploadEnable=false
QingIpcVersion=1.0.0.6
diffUserIdentify=false
libpath=/usr/lib/office6/addons/qing
newshare2=false
uploadFile=false
shareFile=false
DesktopSync=false
SpecifyFolderSync=false
specific_companyintro=true
qingVersion=1
RealTimeUploadSwitchFlag=
SendBy=false
UploadSync=false
crash=1
fileTransfer=false
guestAccount=false
kicDesktopSyncSwitch=false
kicFileTransferSwitch=false
kicSendBySwitch=false
kicShareFileSwitch=false
kicSyncFolderSwitch=false
kicUploadFileSwitch=false
kicUploadSyncSwitch=false
VLGDeviceKey=1790943343060|1791025819733

[usercenter]
overFileSizeUpload_yunkit=true
all\wpsbox\AllDocRadar_Ignore=0
all\wpsbox\MarkShareMsgNewRemind=1
devices\softbuss_file_label=true
funcRegSw\isSupportPluginFilesActionEx=false
funcRegSw\useSyncAssist=1
all\wpsbox\Dispersed_AllDocRadar_Ignore=1
devices\label_sync_page=true
funcRegSw\useSyncAssistV2=1
all\wpsbox\Radar_Ignore\qqtim=1
all\wpsbox\Radar_Ignore\wechat=1
all\wpsbox\Radar_Ignore\webdownload=1
all\wpsbox\Radar_Ignore\desktop=1
welcomeBind=false
cloudspaceinfo\config\enableManager=false

[userinfo]
forceLoginState=false
companyid=
userid=

[clouddisk]
batchRemove=1
supportPMoveFolder=1

[Nse]
IsEnterprise=1

[backup]
DesktopSync=true
SendBy=true
SpecifyFolderSync=true
UploadSync=true
fileTransfer=true
shareFile=true
uploadFile=true

[msgcenter]
MsgCenterMsgVersion=13

[netswitch]
zh_CN\12.1.2_12.1.2.28080_00001.00000001=eyJRUHVzaCI6InRydWUiLCJjcnlwdGNvb2tpZSI6InRydWUiLCJtb2JpbGVQdXNoIjoiZmFsc2UiLCJxaW5pdSI6Im9wZW4iLCJyZXN1bHQiOiJvayIsInJvYW1Ib21lcGFnZVNldHRpbmdHdWlkIjoidHJ1ZSIsInNob3dndWlkZSI6ImZhbHNlIiwidXBkYXRlVGlwSW50ZXJ2YWwiOiIzNjAwMCJ9
