color0 #524343
color1 #ffb4ab
color2 #ffb3b5
color3 #e6bdbd
color4 #e6c08d
color5 #ffb3b5
color6 #e6bdbd
color7 #f0dede
color8 #9f8c8c
color9 #ffb4ab
color10 #ffb3b5
color11 #e6bdbd
color12 #e6c08d
color13 #ffb3b5
color14 #e6bdbd
color15 #f0dede

cursor                #f0dede
cursor_text_color     #1a1111
background            #1a1111
foreground            #f0dede
selection_foreground  #d7c1c1
selection_background  #524343
active_border_color   #ffb3b5
inactive_border_color #524343
url_color             #ffb3b5

active_tab_foreground   #561d22
active_tab_background   #ffb3b5
inactive_tab_foreground #d7c1c1
inactive_tab_background #524343
cursor_trail_color      #d7c1c1
