color0 #4a4739
color1 #ffb4ab
color2 #d7c770
color3 #d0c7a2
color4 #a8d0b5
color5 #d7c770
color6 #d0c7a2
color7 #e8e2d4
color8 #959180
color9 #ffb4ab
color10 #d7c770
color11 #d0c7a2
color12 #a8d0b5
color13 #d7c770
color14 #d0c7a2
color15 #e8e2d4

cursor                #e8e2d4
cursor_text_color     #15130c
background            #15130c
foreground            #e8e2d4
selection_foreground  #ccc6b5
selection_background  #4a4739
active_border_color   #d7c770
inactive_border_color #4a4739
url_color             #d7c770

active_tab_foreground   #383000
active_tab_background   #d7c770
inactive_tab_foreground #ccc6b5
inactive_tab_background #4a4739
cursor_trail_color      #ccc6b5
