[General]
firstTime=false
windowGeometry=@Rect(0 0 942 1012)
windowMaximized=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3\xae\0\0\x3\xba\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false

[DisplaySettings]
bgColorNoMacsRGBA=4294506744
bgColorWidgetRGBA=2281701376
fgColorNoMacsRGBA=4281545523
highlightColorRGBA=4278225151
iconColorRGBA=4281545523
stylePlugin=qt6ct-style

[DkAppManager]
Apps\1\appName=&文件管理器
Apps\1\appPath=OpenDir
Apps\1\objectName=OpenDir
Apps\2\appName=&默认应用
Apps\2\appPath=OpenFile
Apps\2\objectName=OpenFile
Apps\size=2

[GlobalSettings]
language=zh_CN

[SynchronizeSettings]
checkForUpdates=true
disableUpdateInteraction=false
